inp = open("input.txt", "w")
inp.write("Hello, world!")
inp.close()
out = open("output.txt", "w")
out.close()
inp = open("input.txt", "r")
text = inp.read()
inp.close()
out = open("output.txt", "w")
out.write(text + " <copy>")
out.close()
